### ISSUE TITLE
Add CGPA Field to Education Section

### ISSUE THREAD

**Issue by Saksham-13** [Saksham-13/ResumeMaker#2]
### Description
In the current version of our resume maker app, users can input their educational background. However, we're missing a crucial piece of information for many users - their Cumulative Grade Point Average (CGPA). It's a standard metric for educational achievement, and it's essential to include it in the education section of the resumes.

### Proposed Solution
This issue aims to enhance the education section by adding a dedicated CGPA field. Users should be able to provide their CGPA in a standardized format. The CGPA field should be seamlessly integrated into the existing form, allowing users to enter this vital academic information.

### Tasks
- [ ] Modify the user interface to include a CGPA field in the education section.
- [ ] Implement validation to ensure that the CGPA provided by the user conforms to the expected format and range. The CGPA should be between 0-10 if no % symbol is given, and 0-100 if % is included in the input.
- [ ] Provide a real-time message below the input field starting from the moment the user begins input, guiding them on how to format their CGPA and notifying them if the constraints are not met.
- [ ] Update the resume generation process to include the CGPA in the final resume.

**Comment by maazshakeel** [comment]
Can I get assigned?

**Comment by g-anupam** [comment]
can i get assigned

**Comment by Advaith2805** [comment]
Can I get assigned

**Comment by Rhn14** [comment]
can i get assigned/

**Comment by Shaatvika** [comment]
Can I get assigned?

**Comment by safelyvik** [comment]
gimme the issue

**Comment by Saksham-13** [comment]
> Can I get assigned

Yes

Read the Readme and get started

**Comment by Nii-khil** [comment]
Can I get assigned?

**Comment by nsashank25** [comment]
Can I get assigned?

**Comment by sssai44** [comment]
Can I get assigned?

**Comment by Sadhana-24** [comment]
Can I get assigned?

**Comment by sid-nc** [comment]
can i get assigned

**Comment by uditreddys** [comment]
CAN I GET THIS ASSIGNED

**Comment by PsychCodez** [comment]
Can i get assigned

**Comment by Saksham-13** [comment]
> CAN I GET THIS ASSIGNED

Are u assigned anywhere else?

**Comment by rarelycalmya** [comment]
can i get assigned?

**Comment by komulannister** [comment]
can i get assigned to this?

**Comment by Ananya-Kini** [comment]
can you pls assign this to me

**Comment by Python-is-better-than-Java** [comment]
Can I get this assigned?

**Comment by anshiiJ** [comment]
can i get assigned pls?

**Comment by N0Xl0US** [comment]
assign me pls

**Comment by SKNAID** [comment]
Can i be assigned to the issue #2

**Comment by amrit-george** [comment]
can i be assigned to this issue?

**Comment by harveen-10** [comment]
can i be assigned to this issue?

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by BhavikaPradeep** [comment]
i wanna get assigned please

**Comment by akdino** [comment]
can i get this assigned

**Comment by 7Akshu77** [comment]
can i get assigned this?

**Comment by Saksham-13** [comment]
You can all send PR for this, I will merge the best one.
